### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by ayoubserti** [Lnd-stoL/qmake2cmake#1]
Hello, 
I tried to use your script on Windows but i get an error:

```
Traceback (most recent call last):
  File "qmake2cmake.py", line 330, in <module>
    if parser.input_file != "":
AttributeError: 'ArgumentParser' object has no attribute 'input_file'
```

**Comment by Lnd-stoL** [comment]
Hi.
Haven't updated this repo for a long time. Just uploaded my actual version of the script without that bug now.
Actually the error was missing line:
`parser = parser.parse_args()`
and the issue was not Windows only.

**Comment by ayoubserti** [comment]
Hi, 
thank you. i will test and come back to you
